### ISSUE TITLE
About the package logger

### ISSUE THREAD

**Issue by chickensoupman** [oval-group/smooth-topk#10]
The package ‘logger’ does not have those attributes in the author code, such as 'logger.Experiment'. Could you provide detailed information about the logger?

**Comment by lberrada** [comment]
You can find a reference about logger in the requirements: https://github.com/oval-group/smooth-topk/blob/master/requirements.txt#L6

The code is expected to run correctly with these requirements, let me know if it does not.

**Comment by chickensoupman** [comment]
> You can find a reference about logger in the requirements: https://github.com/oval-group/smooth-topk/blob/master/requirements.txt#L6
> 
> The code is expected to run correctly with these requirements, let me know if it does not.

I'm sorry my friend, I tried pip install logger and pip install git+git://github.com/oval-group/logger#egg=v0.3, but it doesn't work. I am a rookie, forgive my stupidity. Here is the error code

AttributeError: module 'logger' has no attribute 'Experiment'

**Comment by lberrada** [comment]
You're correct, it seems that the syntax for using a specific git version to install has changed since these requirements were written. Please try instead `pip install git+git://github.com/oval-group/logger@v0.3`

**Comment by chickensoupman** [comment]
> You're correct, it seems that the syntax for using a specific git version to install has changed since these requirements were written. Please try instead `pip install git+git://github.com/oval-group/logger@v0.3`

It works! Thanks a lot!

**Comment by lberrada** [comment]
Great, closing the issue then.
