### ISSUE TITLE
SVM Weight Decay: `2.5e-4` or `2.5e-5`?

### ISSUE THREAD

**Issue by bamos** [oval-group/smooth-topk#4]
I noticed that in [imagenet_subsets_svm.sh](https://github.com/oval-group/smooth-topk/blob/master/src/scripts/imagenet_subsets_svm.sh), the weight-decay is set to `2.5e-4`, but the paper says that it was set to `2.5e-5`. Which one is correct?

**Comment by lberrada** [comment]
It should be 2.5e-5, thanks for catching this!

**Comment by bamos** [comment]
Thanks for the quick response!

**Comment by lberrada** [comment]
I am closing this, feel free to open issues if there are other problems.
