### ISSUE TITLE
*** RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

### ISSUE THREAD

**Issue by fedshyvana** [oval-group/smooth-topk#8]
Hi, thank you for providing the code. 
I tried to use the loss function as follows:
top1_loss = SmoothTop1SVM(n_classes=4)
x = torch.rand(1,4)
y = torch.tensor([0]).long()
loss = top1_loss(x,y)

the above code works. 

however, if I do:
x = x.cuda()
y = y.cuda()
loss = top1_loss(x,y)

it no longer works, and this is what I got:
*** RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'other'

I am using pytorch 1.1.
any thoughts? Thank you!

**Comment by albanD** [comment]
Hi,

The loss contains some buffers so you need to send the loss Module to the GPU the same way you do it with your model: `top1_loss.cuda()`.

**Comment by fedshyvana** [comment]
> Hi,
> 
> The loss contains some buffers so you need to send the loss Module to the GPU the same way you do it with your model: `top1_loss.cuda()`.

Hi! Thank you for the quick reply. I tried that but it does not seem to solve the issue. It appears the issue comes from utils.py, functions delta() and split(). where in torch.ne(), the "labels" variable is defined on the cpu. I am not sure if that's actually the issue but inside those two functions, once I moved "labels" to cuda, I no longer get the error. However, a second issue arises:

  File "main.py", line 237, in train_loop
    loss.backward()
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/fm813/.local/lib/python3.7/site-packages/topk-1.0-py3.7.egg/topk/polynomial/sp.py", line 92, in backward
  File "/home/fm813/.local/lib/python3.7/site-packages/topk-1.0-py3.7.egg/topk/polynomial/grad.py", line 54, in d_logS_d_expX
AttributeError: 'int' object has no attribute 'torch'

It appears this issue is also present when I am using the loss function for cpu only tensors. Any ideas? Thank you once again.

**Comment by lberrada** [comment]
Hi, I'm not able to locally reproduce the issue (with pytorch 1.2). The following short script runs for me:
```python
import topk
import torch

top1_loss = topk.SmoothTop1SVM(n_classes=4)
x = torch.rand(1, 4, requires_grad=True)
y = torch.tensor([0]).long()
loss = top1_loss(x, y)
loss.backward()
print(x.grad)
```
I don't have a GPU to test it, but I would also expect the following to work:
```python
import topk
import torch

top1_loss = topk.SmoothTop1SVM(n_classes=4).cuda()
x = torch.rand(1, 4, requires_grad=True).cuda()
y = torch.tensor([0]).long().cuda()
loss = top1_loss(x, y)
loss.backward()
print(x.grad)
```
Can you try running these scripts without modifying the internal code?

**Comment by fedshyvana** [comment]
> Hi, I'm not able to locally reproduce the issue (with pytorch 1.2). The following short script runs for me:
> 
> ```python
> import topk
> import torch
> 
> top1_loss = topk.SmoothTop1SVM(n_classes=4)
> x = torch.rand(1, 4, requires_grad=True)
> y = torch.tensor([0]).long()
> loss = top1_loss(x, y)
> loss.backward()
> print(x.grad)
> ```
> 
> I don't have a GPU to test it, but I would also expect the following to work:
> 
> ```python
> import topk
> import torch
> 
> top1_loss = topk.SmoothTop1SVM(n_classes=4).cuda()
> x = torch.rand(1, 4, requires_grad=True).cuda()
> y = torch.tensor([0]).long().cuda()
> loss = top1_loss(x, y)
> loss.backward()
> print(x.grad)
> ```
> 
> Can you try running these scripts without modifying the internal code?

Hi! Thanks once again. I tried these snippets and that they both work. That's great. However, I found out that my actual problem was with SmoothTopkSVM, which I also use in my code. For example, when testing, the following code snippet produces the error (without modifying internal code):

```top2_loss = topk.SmoothTopkSVM(n_classes=4, k=2)
x = torch.rand(1, 4, requires_grad=True)
y = torch.tensor([0]).long()
loss = top2_loss(x, y)
loss.backward()
print(x.grad)
```

```
Traceback (most recent call last):
  File "test_top.py", line 17, in <module>
    loss.backward()
  File "//anaconda3/envs/machine_learning/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "//anaconda3/envs/machine_learning/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "//anaconda3/envs/machine_learning/lib/python3.7/site-packages/topk-1.0-py3.7.egg/topk/polynomial/sp.py", line 92, in backward
  File "//anaconda3/envs/machine_learning/lib/python3.7/site-packages/topk-1.0-py3.7.egg/topk/polynomial/grad.py", line 54, in d_logS_d_expX
AttributeError: 'int' object has no attribute 'torch'
```

**Comment by lberrada** [comment]
Okay, I'm able to reproduce the issue thanks. The problem seems to be a failing edge case when k=2. The problem should disappear for k > 2.

**Comment by fedshyvana** [comment]
> Okay, I'm able to reproduce the issue thanks. The problem seems to be a failing edge case when k=2. The problem should disappear for k > 2.

Hi, thank you for looking into this. Unfortunately, my specific application requires the case of k=2. Do you perhaps have any suggestions on any other good algorithms I can try to optimize a top-k loss using SGD? Thank you so much!

**Comment by lberrada** [comment]
Hi, this issue is nothing fundamental, I'll try to push a fix for it in the next few days. If you're looking for other methods, you may want to check out the [LML layer paper by Brandon Amos et al.](https://arxiv.org/abs/1906.08707), which includes pytorch code as well.
